### ISSUE TITLE
How to Make this script work for mirroring debian 

### ISSUE THREAD

**Issue by Reyota** [Gargravarr2112/mirror-rsync#5]
Hello I want to try mirroring debian with this script but after editing for what i want to mirror debian, i get stuck after running this script at gunzip because can't find .gz

**Comment by Gargravarr2112** [comment]
Hi, sorry for the delay in replying. So I managed to reproduce the problem, Debian uses symlinks to 'by-hash' which I haven't seen with Ubuntu. I think I know how to fix this.

**Comment by Gargravarr2112** [comment]
Hi, please try this branch and see if it works for you.

**Comment by Reyota** [comment]
Ahhh okay thanks, but for now i use 2 script mirroring for debian, because when i use 1 script, this script just can extract Packages.gz  and for Packages.xz he can't extract because can't use gunzip, so i make 2 script for debian, 1 For .gz Packages and 1 for .xz Packages

**Comment by Reyota** [comment]
And after that i combine 2 pool list update and i run with another script for delete anything when not listed update pool package, because im so bad for programming

**Comment by Gargravarr2112** [comment]
Interesting, I had assumed gunzip was available everywhere. I can check for gunzip and use the XZ file instead if it would help.

**Comment by Reyota** [comment]
im not use gunzip for xz i use xz-utils for extract xz package

**Comment by Gargravarr2112** [comment]
Yep, I understand, gz and xz are two different compression algorithms.

I just pushed a commit to the branch that will use XZ if it can't find gzip, please try that.

**Comment by Reyota** [comment]
okay thanks bro
